export const Dares = [
    'Chống đẩy 5 cái',
    'Plank 30s',
    'Squat 20 cái',
    'Uống 3 ly',
    'Uống 1 ly',
    'Gập bụng 10 cái',
    'Cho người ấy xem lịch sử trình duyệt',
    'Cho người ấy xem lịch sử tin nhắn',
    'Để người đối diện cắn vào tay bạn 1 cái',
    'Tháo 3 đồ bất kỳ trên người bạn',
    'Nhịn thở trong 30s (nhờ người ấy bịt mũi)',
    'Để người ấy thổi vào tai bạn trong 10s',
    'Để người ấy búng tai bạn',
    'Để người ấy búng trán bạn',
    'Để người ấy búng mũi bạn',
    'Để người ấy đánh bạn 1 cái',
    'Để người ấy cấu/véo bạn 1 cái thật đau',
    'Để người ấy vẽ hình lên người bạn/hoặc make-up cho bạn',
    'Để người ấy tát bạn 1 cái',
];
