export const Truths = [
    'Kể 1 câu chuyện về 1 thành viên trong gia đình mình? (người ấy có thể lựa chọn hộ bạn)',
    'Sinh nhật, Số di động, Mã căn cước công dân của người ấy là gì?',
    'Bạn có nhớ tên đầy đủ của bố mẹ người ấy không?',
    'Kể về 1 thói quen xấu khó bỏ của bản thân?',
    "Thứ gì khiến cho bạn muốn 'turned on'?",
    'Bạn đã bao giờ nói dối người ấy về chuyện gì chưa?',
    'Bạn còn nhớ buổi hẹn hò đầu tiên với người ấy, 2 bạn đã tiến xa tới mức nào không?',
    'Trong mắt bạn, điểm trừ lớn nhất của 1 người khác giới là gì?',
    'Bạn đã từng crush ai khi còn đang đi học?',
    'Điều gì khiến bạn vừa vui vừa khóc khi biết đến nó?',
    'Cân nặng của người ấy hiện tại là bao nhiêu nhỉ? (thêm bớt 1kg cũng được nhé)',
    'Chiều cao của người ấy hiện tại là bao nhiêu nhỉ?',
    'Nếu đi du lịch, người ấy của bạn sẽ chọn Biển hay Núi?',
    'Nếu gọi đồ uống, người ấy của bạn sẽ chọn Trà hay Cafe?',
    'Món quà tệ nhất mà bạn được nhận từ người ấy là gì?',
    'Bạn dự định có bao nhiêu người con?',
    'Điều lớn nhất mà bạn muốn người ấy thay đổi là gì?',
    'Bạn đang sợ điều gì nhất trong mối quan hệ tình cảm hiện tại?',
    'Theo bạn, điều tuyệt vời nhất mà 2 bạn đã từng cùng làm với nhau là gì?',
    'Theo bạn, 1 kì nghỉ lí tưởng bên cạnh người ấy cần có những điều gì?',
    'Bạn có biết màu sắc yêu thích của người ấy không?',
    'Bạn có biết người ấy thích thời điểm nào nhất trong năm không?',
    'Bạn có muốn phẫu thuật thẩm mỹ ở bộ phận nào trên cơ thể không? Tại sao có (hoặc tại sao không?)',
    'Nụ hôn đầu của bạn vào thời điểm nào nhỉ?',
    'Bạn có bao giờ stalk người yêu cũ của mình không?',
    'Bạn có từng hẹn hò với ai hơn tuổi chưa?',
    'Bạn có từng hẹn hò với ai kém tuổi chưa?',
    'Bạn đã bao giờ gửi nhầm tin nhắn cho ai khác (mà đáng lẽ phải gửi cho người ấy) chưa?',
    'Bạn có bao giờ khởi tạo 1 tin đồn về 1 người mà bạn ghét không?',
    'Có điều gì bạn cực kỳ thích hoặc cực kỳ muốn, hưng bạn hi sinh điều đó vì người ấy không?',
    'Việc nhà nào mà bạn ghét làm nhất?',
    'Bạn nghĩ tới ngay con vật nào khi nhắc về người ấy?',
    'Bạn có tin vào "Tình yêu sét đánh" không?',
    'Bạn có thấy người ấy có mùi gì lạ ở bộ phận nào trên cơ thể không?',
    'Nghê thứ 2 của bạn sẽ là gì nếu nghề hiện tại của bạn không có đất dụng võ nữa?',
    'Chia sẻ về 1 điều mà bạn nghĩ có thể làm tan vỡ 1 mối quan hệ?',
    'Miêu tả lần đầu bạn được táy máy tay chân với người ấy đi',
    'Bạn nhớ tới điều gì ở người ấy khi người ấy không bên cạnh bạn?',
    'Món ăn yêu thích của người ấy?',
    'Món ăn cực ghét của người ấy?',
    'Bạn muốn chạm vào đâu trên cơ thể người ấy?',
    'Nghĩ 1 thử thách bất kỳ cho người ấy và bắt người ấy phải thực hiện (Nếu không chịu thực hiện thì làm theo dare của lá bài này)',
    'Kể tên 5 brand BCS mà bạn biết (Không kể được thì thực hiện dare)',
];
