const AUTHENTICATE_ROUTE = {
    LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
};

const APP_ROUTE = {
    MAIN_TAB: 'MAIN_TAB',
};

const EATING_ROUTE = {
    ROOT: 'EATING_ROOT',
    LIST: 'EATING_LIST',
    CREATE: 'EATING_CREATE',
    EDIT: 'EATING_EDIT',
    DETAILS: 'EATING_DETAILS',
};

const PLAYING_ROUTE = {
    ROOT: 'PLAYING_ROOT',
    LIST: 'PLAYING_LIST',
    CREATE: 'PLAYING_CREATE',
    EDIT: 'PLAYING_EDIT',
    DETAILS: 'PLAYING_DETAILS',
};
const PLANNING_ROUTE = {
    ROOT: 'PLANNING_ROOT',
    LIST: 'PLANNING_LIST',
    CREATE: 'PLANNING_CREATE',
    EDIT: 'PLANNING_EDIT',
    DETAILS: 'PLANNING_DETAILS',
};

const SETTING_ROUTE = {
    ROOT: 'SETTING_ROOT',
    SETTINGS: 'SETTINGS',
};

const TAB_NAVIGATION_ROOT = {
    EATING_ROUTE,
    PLAYING_ROUTE,
    PLANNING_ROUTE,
    SETTING_ROUTE,
};

export { APP_ROUTE, TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE };
